import { IList } from "./IList";

export const LIST: IList[] = [
    {
        id: "AxelID",
        username: "Axel",
        title: "Perfumes nicho",
        pfp: "/user/profile-pic/profile1.jpg",
        premium: true,
        coffee: false,
        perfumes: [
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
        ]
    },
    {
        id: "JakobID",
        username: "Jakob",
        title: "TÍTULO SUPER LARGO PARA PROBAR SI ESTO ENCAJA BIEN O NO",
        pfp: "/user/profile-pic/profile2.jpg",
        premium: false,
        coffee: true,
        perfumes: [
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
        ]
    },
    {
        id: "KevinID",
        username: "Kevin",
        title: "Perfumes verano",
        pfp: "/user/profile-pic/profile3.png",
        premium: false,
        coffee: false,
        perfumes: [
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
        ]
    },{
        id: "AxelID",
        username: "Axel",
        title: "Perfumes nicho",
        pfp: "/user/profile-pic/profile1.jpg",
        premium: true,
        coffee: false,
        perfumes: [
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
        ]
    },
    {
        id: "JakobID",
        username: "Jakob",
        title: "TÍTULO SUPER LARGO PARA PROBAR SI ESTO ENCAJA BIEN O NO",
        pfp: "/user/profile-pic/profile2.jpg",
        premium: false,
        coffee: true,
        perfumes: [
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
        ]
    },
    {
        id: "KevinID",
        username: "Kevin",
        title: "Perfumes verano",
        pfp: "/user/profile-pic/profile3.png",
        premium: false,
        coffee: false,
        perfumes: [
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
        ]
    },
    {
        id: "AxelID",
        username: "Axel",
        title: "Perfumes nicho",
        pfp: "/user/profile-pic/profile1.jpg",
        premium: true,
        coffee: false,
        perfumes: [
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
        ]
    },
    {
        id: "JakobID",
        username: "Jakob",
        title: "TÍTULO SUPER LARGO PARA PROBAR SI ESTO ENCAJA BIEN O NO",
        pfp: "/user/profile-pic/profile2.jpg",
        premium: false,
        coffee: true,
        perfumes: [
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
        ]
    },
    {
        id: "KevinID",
        username: "Kevin",
        title: "Perfumes verano",
        pfp: "/user/profile-pic/profile3.png",
        premium: false,
        coffee: false,
        perfumes: [
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
        ]
    }
]