import { IListas } from "../../interfaces/IListas";

export const LIST: IListas[] = [
    {
        id: "AxelID",
        nombreUsuario: "Axel",
        titulo: "Perfumes nicho",
        pfp: "/user/profile-pic/profile1.jpg",
        premium: true,
        cafe: false,
        perfumes: [
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
        ]
    },
    {
        id: "JakobID",
        nombreUsuario: "Jakob",
        titulo: "TÍTULO SUPER LARGO PARA PROBAR SI ESTO ENCAJA BIEN O NO",
        pfp: "/user/profile-pic/profile2.jpg",
        premium: false,
        cafe: true,
        perfumes: [
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
        ]
    },
    {
        id: "KevinID",
        nombreUsuario: "Kevin",
        titulo: "Perfumes verano",
        pfp: "/user/profile-pic/profile3.png",
        premium: false,
        cafe: false,
        perfumes: [
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
        ]
    },
    {
        id: "AxelID",
        nombreUsuario: "Axel",
        titulo: "Perfumes nicho",
        pfp: "/user/profile-pic/profile1.jpg",
        premium: true,
        cafe: false,
        perfumes: [
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
        ]
    },
    {
        id: "JakobID",
        nombreUsuario: "Jakob",
        titulo: "TÍTULO SUPER LARGO PARA PROBAR SI ESTO ENCAJA BIEN O NO",
        pfp: "/user/profile-pic/profile2.jpg",
        premium: false,
        cafe: true,
        perfumes: [
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
        ]
    },
    {
        id: "KevinID",
        nombreUsuario: "Kevin",
        titulo: "Perfumes verano",
        pfp: "/user/profile-pic/profile3.png",
        premium: false,
        cafe: false,
        perfumes: [
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
        ]
    },
    {
        id: "AxelID",
        nombreUsuario: "Axel",
        titulo: "Perfumes nicho",
        pfp: "/user/profile-pic/profile1.jpg",
        premium: true,
        cafe: false,
        perfumes: [
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
        ]
    },
    {
        id: "JakobID",
        nombreUsuario: "Jakob",
        titulo: "TÍTULO SUPER LARGO PARA PROBAR SI ESTO ENCAJA BIEN O NO",
        pfp: "/user/profile-pic/profile2.jpg",
        premium: false,
        cafe: true,
        perfumes: [
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
        ]
    },
    {
        id: "KevinID",
        nombreUsuario: "Kevin",
        titulo: "Perfumes verano",
        pfp: "/user/profile-pic/profile3.png",
        premium: false,
        cafe: false,
        perfumes: [
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
            "/perfume-info/perfume/ELDO/eldo-perfume.webp",
        ]
    }
]